### ISSUE TITLE
Многострочные комментарии обрабатываются как ошибка.

### ISSUE THREAD

**Issue by mirilled** [AlekseyZhelo/idea-mob-plugin#1]
Скриптовой язык Проклятых Земель поддерживает многострочные комментарии, но плагин ругается на них как на ошибку в синтаксисе.
![image](https://user-images.githubusercontent.com/22909153/77057879-b0089080-69e5-11ea-938f-bd9e211ecaee.png)

**Comment by AleksZhelo** [comment]
Исправлено в 1.1.
